from enum import Enum

class AccionSemaforo(Enum):
    CAMBIAR_A_VERDE = "CAMBIAR_A_VERDE"
    CAMBIAR_A_ROJO = "CAMBIAR_A_ROJO"
    EXTENDER_VERDE = "EXTENDER_VERDE"
    # Additional values used by the system rules engine
    EXTENDER_VERDE_Y_GENERAR_ALERTA = "EXTENDER_VERDE_Y_GENERAR_ALERTA"
    OLA_VERDE = "OLA_VERDE"
    PRIORIZAR_VIA = "PRIORIZAR_VIA"
    MANTENER_TEMPORIZACION = "MANTENER_TEMPORIZACION"
    RESTAURAR_TEMPORIZACION = "RESTAURAR_TEMPORIZACION"
    SIN_ACCION = "SIN_ACCION"

